site_name: Guía de publicación de CSV
site_url:  https://gbvitrano.github.io/guidaPraticaPubblicazioneCSV-ES/
site_description: Guía práctica para la publicación de datos tabulares en archivos CSV

repo_url: https://github.com/gbvitrano/guidaPraticaPubblicazioneCSV-ES
repo_name: guidaPubblicazioneCSV-ES
edit_uri: edit/main/docs/

copyright: 'Esta guía es un proyecto de la<a href="https://twitter.com/ondatait" target="_blank"> asociación onData</a> | licencia <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.es" target="_blank">CC BY-SA 4.0</a>'

theme:
  name: material
  icon:
    logo: material/table
  highlightjs: true
  custom_dir: overrides
  favicon: imgs/favicon.ico
  palette:
    - scheme: preference
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  language: es
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  font:
    text: Montserrat
    #code: Cutive Mono
    code: Fira Code


nav:
    - Home: index.md
    - Guía:
      - guía/index.md
      - Formato de Datos tabulares: guía/formato_datos_tabulares.md
      - Diccionarios de Datos: guía/diccionarios_datos.md
      - Pautas para publicar archivo CSV:
          - guía/guidelines_publication/index.md
          - Línea única de cabecera opcional: guía/guidelines_publication/P01_Línea_única_cabecera_opcional.md
          - Registro único por fila: guía/guidelines_publication/P02_Registro_único_por_fila.md
          - Nombrado de columnas: guía/guidelines_publication/P03_Nombrado_de_columnas.md
          - Estructuras de datosverticales vs horizontales: guía/guidelines_publication/P04_Estructuras_de_datosverticales_vs_horizontales.md
          - Tratamiento de valores desconocidos: guía/guidelines_publication/P05_Tratamiento_de_valores_desconocidos.md
          - Subtotales, totales o agrupamientos: guía/guidelines_publication/P06_Subtotales_totales_o_agrupamientos.md
          - Tipos de datos: guía/guidelines_publication/P07_Tipos_de_datos.md
          - Estandarización de valores de los campos: guía/guidelines_publication/P08_Estandarización_de_valores_de_los_campos.md
      - Pautas para exportar/importar datos tabulares desde herramientas de hojas de cálculo a CSV:
         - guía/exportar_importar/index.md    
      - Otras consideraciones sobre archivos CSV:
          - guía/otras/index.md
      - Toolbox para archivos CSV:
          -  guía/toolbox_archivos/index.md
      - Dónde encontrar buenos ejemplos de datos en format CSV:
          - guía/ejemplos/index.md
      - Enlaces de interés:
         - guía/enlaces_de_interés/index.md
      - Anexo I:
          - guía/taxonomías/index.md
      - Credits:
         - guía/credits/index.md
          
    - Involucrarse: partecipa.md
    - Nota: note_redazione.md

extra:
 social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ondatait
      
extra:
  alternate:
    - name: Español
      link: 
      lang: es
    - name: Italiano
      link: https://ondata.github.io/guidaPraticaPubblicazioneCSV/
      lang: it

# foglio di stile personalizzato
extra_css:
  - stylesheets/style.css

plugins:
  - search:
      lang: es
  - mkdocstrings
  - mermaid2


extra_javascript:
#  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
#  - javascripts/tables.js
  - javascripts/varie.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
- admonition
- md_in_html
- attr_list
- footnotes
- meta
- mkdocs-click
- pymdownx.keys
- pymdownx.betterem:
      smart_enable: all
- pymdownx.caret
- pymdownx.critic:
      mode: view
- pymdownx.details
- pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
- pymdownx.tabbed
- pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
- pymdownx.tilde
- toc:
      permalink: true
      toc_depth: 3

